### ISSUE TITLE
Sketch too big with Trinket 5v

### ISSUE THREAD

**Issue by robertcasanova** [adafruit/Adafruit_LED_Backpack#32]
Hi, i was not able to load any example on Trinket because "Sketch is too Big"

For example with Matrix 8x8 example i have:

`Sketch uses 6,628 bytes (124%) of program storage space. Maximum is 5,310 bytes.`

The only working example is the HT16K33.

Do you have any suggestion?? 

Thank you for your help.

**Comment by PaintYourDragon** [comment]
The Adafruit_GFX library (which most of the LED backpack examples rely on) is too large for the Trinket's program space. HT16K33 only works because it bypasses GFX, accessing the matrix buffer directly.
Option 1: use a more capable small-form-factor board (e.g. Pro Trinket or Teensy 2.0).
Option 2: use a programming strategy similar to the HT16K33 example (see the Space Invader Pendant guide on the Adafruit Learning System) - this means NO graphics primitives (lines, text, etc.), everything must be bitmapped manually, can be a bit of a challenge.
